name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup SlnLauncher
      run: choco install slnlauncher
    - name: Create solution
      run: slnlauncher -q -u- -o- -b . NugetHelper.slnx
    - name: Restore dependencies
      run: |
        .\SetEnvVars.ps1
        dotnet restore
    - name: Build
      run: |
        .\SetEnvVars.ps1
        dotnet build --no-restore
    - name: Test
      run: |
        .\SetEnvVars.ps1
        dotnet test --no-build --verbosity normal
